#!/bin/bash
##begin## define the common command #

#ECHO=`type -path echo`
ECHO='echo '
AWK=`type -path awk`
GREP=`type -path grep`
SED=`type -path sed`
ICONV=`type -path iconv`

###end### define the common command #
declare -a datafrom
datafrom=(ip138 ip5 x123cha chinaz x114la ip_cn x21andy)
showcmd=`$ECHO ${datafrom[1]}`


###Functions#####
function ip138(){
    _URL_IP138='http://ip138.com/ips138.asp?action=2&ip='
    if [ -z $1 ] ; then 
       return 1
    fi

    _URL_CUR=${_URL_IP138}${1}

    _location=`curl -s "${_URL_CUR}" | $GREP '<ul class="ul1"><li>' |$AWK  -F'</?li[^>]*?>' '{print $2,$4}' `
 #$AWK -F'[><]+' '{print $5}' 

    _location_utf8=`$ECHO $_location | $ICONV -f gbk -t utf-8 `

    $ECHO $_location_utf8
}
function ip5(){
    _URL_IP5='http://www.ip5.me/index.php'
    if [ -z $1 ] ; then
        return 1
    fi
    _POST_DATA="s=$1&doit=1"
    _URL_CUR=$_URL_IP5

    _location=`curl -s -d "${_POST_DATA}" "${_URL_CUR}" | $GREP '<div id="ip_pos"' | $AWK -F'</?[^>]*?>' '{print $3}' ` 

    _location_utf8=`$ECHO $_location | $ICONV -f gbk -t utf-8 `

    $ECHO $_location_utf8

}
function x123cha(){
    _URL_123CHA='http://www.123cha.com/ip/?q='
    if [ -z $1 ] ; then
        return 1
    fi

    _URL_CUR=${_URL_123CHA}${1}

    _location=`curl -s "${_URL_CUR}" | $GREP '<div id="cresult"' | $SED -e 's/&nbsp;//g'| $AWK -F'</?[^>]*?>' '{print $3,$4,$5,$6}' `

    _location_utf8=`$ECHO $_location `

    $ECHO $_location_utf8
}
function x21andy(){
    _URL_21ANDY='http://www.21andy.com/ip/?ip='
    if [ -z $1 ] ; then
        return 1
    fi

    _URL_CUR=${_URL_21ANDY}${1}

    _location=`curl -s "${_URL_CUR}" | $GREP '<h2>' | $AWK -F'</?[^>]*?>' '{print $7}' ` 

    _location_utf8=`$ECHO $_location `

    $ECHO $_location_utf8
}
function ip_cn(){
    _URL_IPCN='http://www.ip.cn/getip.php?action=queryip&from=web&ip_url='
    if [ -z $1 ] ; then
        return 1
    fi

    _URL_CUR=${_URL_IPCN}${1}

    _location=`curl -s "${_URL_CUR}" | $AWK -F'</?[^>]*?>' '{print $5}' `

    _location_utf8=`$ECHO $_location | $ICONV -f gbk -t utf-8 `

    $ECHO $_location_utf8
}
function x114la(){
    _URL_114LA='http://tool.114la.com/ip/'
    if [ -z $1 ] ; then
        return 1
    fi

    _URL_CUR=${_URL_114LA}${1}

    _location=`curl -s "${_URL_CUR}" |$SED -e 's/>/>\n/g' | $SED -n -e ' /<table/,/<\/table>/p'  | $AWK  'BEGIN{FS="<[^>]*>" ;RS="|";}{print $10,$12,$16,$18,$22,$24}'`
#|$SED -e 's/>/>\n/g' | $SED -n -e '/^<table/p;/^<\/table>$/p;'  ` #|$AWK -F'</?[^>]*?>' 'RT ~ /t[hd]/ { print $0}'  ` # | $SED -e 's/&nbsp;//g'| $AWK -F'</?[^>]*?>' '{print $3,$4,$5,$6}' `

    $ECHO $_location
    _location_utf8=`$ECHO $_location `

    #$ECHO $_location_utf8
}

function chinaz(){
    _URL_CHINAZ='http://ip.chinaz.com/?IP='

    if [ -z $1 ] ; then
        return 1
    fi

    _URL_CUR=${_URL_CHINAZ}${1}

    _location=`curl -s "${_URL_CUR}" | $GREP '<strong class="red"' | $SED -e 's/\(<strong class="red">\)/\n\\1/g'| tail -n 1 | $AWK -F'</?[^>]*?>' '{print $2}' | cut -d'>' -f5 ` 
   #| $GREP '<span class="info3"' | $AWK -F'</?[^>]*?>' '{print $5}' `

   # | $GREP '<div id="cresult"' | $SED -e 's/&nbsp;//g'| $AWK -F'</?[^>]*?>' '{print $3,$4,$5,$6}' `
    
    _location_utf8=`$ECHO $_location `
    
    $ECHO $_location_utf8
}
function iplookup(){
        while read line;do
                ip=`$ECHO $line | cut -d: -f1`
                #_location=`curl -s  "http://ip138.com/ips138.asp?ip=${ip}&action=2" | $GREP '<ul class="ul1"><li>' |$AWK -F'[><]+' '{print $5}' `
                _location=`ip138 $ip`
                $ECHO $ip $_location
        done < $1
}

function usage(){
    $ECHO "Usage: $0 [OPTION]
   -i [ip adress]
   -f [a file]
"
}
function version(){
    VERSION='0.1.0'
    AUTHOR='dolfly'
    COPYRIGHT='Copyright (C) 2002-2010 DOLFLY , Inc. <dolfly@foxmail.com>'
    $ECHO $0" "${VERSION} 
    $ECHO $COPYRIGHT
}

#####MAIN#####
case $1 in
-f)
        shift
        if [ -r $1 ] ;then
            iplookup $1
        else 
            $ECHO "file $1 not exists." 
            exit
        fi
        
;;
-i)
        shift
               # _location=`curl -s  "http://ip138.com/ips138.asp?ip=$1&action=2" |$GREP '<ul class="ul1"><li>' |$AWK -F'[><]+' '{print $5}'`
               #_location
               $ECHO $1 
               for showcmd in ${datafrom[@]} ;do 
                   _location=`$showcmd $1` 
                   $ECHO -e  $showcmd"\t:\t"$_location 
               done
        #$ECHO $1 $_location | $ICONV -f gbk -t utf-8 
;;
-v)     
    version
    ;;
*)
        usage
;;
esac
